/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NotFoundImport } from './routes/not-found'
import { Route as DashboardLayoutImport } from './routes/_dashboardLayout'
import { Route as ChatLayoutImport } from './routes/_chatLayout'
import { Route as SplatImport } from './routes/$'
import { Route as IndexImport } from './routes/index'
import { Route as RegistrationIndexImport } from './routes/registration/index'
import { Route as LogoutIndexImport } from './routes/logout/index'
import { Route as RegistrationSuccessImport } from './routes/registration/success'
import { Route as RegistrationErrorImport } from './routes/registration/error'
import { Route as RegistrationConfirmImport } from './routes/registration/confirm'
import { Route as RegistrationCancelImport } from './routes/registration/cancel'
import { Route as LoginSuccessImport } from './routes/login/success'
import { Route as DashboardLayoutDashboardIndexImport } from './routes/_dashboardLayout/dashboard/index'
import { Route as ChatLayoutChatIndexImport } from './routes/_chatLayout/chat/index'
import { Route as ChatLayoutChatIdImport } from './routes/_chatLayout/chat/$id'
import { Route as DashboardLayoutDashboardUsersIndexImport } from './routes/_dashboardLayout/dashboard/users/index'
import { Route as DashboardLayoutDashboardSettingsIndexImport } from './routes/_dashboardLayout/dashboard/settings/index'
import { Route as DashboardLayoutDashboardUsersCreateImport } from './routes/_dashboardLayout/dashboard/users/create'
import { Route as DashboardLayoutDashboardSettingsSuccessImport } from './routes/_dashboardLayout/dashboard/settings/success'
import { Route as DashboardLayoutDashboardUsersUpdateIdImport } from './routes/_dashboardLayout/dashboard/users/update/$id'
import { Route as DashboardLayoutDashboardUsersDeleteSuccessImport } from './routes/_dashboardLayout/dashboard/users/delete/success'
import { Route as DashboardLayoutDashboardUsersDeleteIdImport } from './routes/_dashboardLayout/dashboard/users/delete/$id'

// Create/Update Routes

const NotFoundRoute = NotFoundImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRoute,
} as any)

const DashboardLayoutRoute = DashboardLayoutImport.update({
  id: '/_dashboardLayout',
  getParentRoute: () => rootRoute,
} as any)

const ChatLayoutRoute = ChatLayoutImport.update({
  id: '/_chatLayout',
  getParentRoute: () => rootRoute,
} as any)

const SplatRoute = SplatImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RegistrationIndexRoute = RegistrationIndexImport.update({
  id: '/registration/',
  path: '/registration/',
  getParentRoute: () => rootRoute,
} as any)

const LogoutIndexRoute = LogoutIndexImport.update({
  id: '/logout/',
  path: '/logout/',
  getParentRoute: () => rootRoute,
} as any)

const RegistrationSuccessRoute = RegistrationSuccessImport.update({
  id: '/registration/success',
  path: '/registration/success',
  getParentRoute: () => rootRoute,
} as any)

const RegistrationErrorRoute = RegistrationErrorImport.update({
  id: '/registration/error',
  path: '/registration/error',
  getParentRoute: () => rootRoute,
} as any)

const RegistrationConfirmRoute = RegistrationConfirmImport.update({
  id: '/registration/confirm',
  path: '/registration/confirm',
  getParentRoute: () => rootRoute,
} as any)

const RegistrationCancelRoute = RegistrationCancelImport.update({
  id: '/registration/cancel',
  path: '/registration/cancel',
  getParentRoute: () => rootRoute,
} as any)

const LoginSuccessRoute = LoginSuccessImport.update({
  id: '/login/success',
  path: '/login/success',
  getParentRoute: () => rootRoute,
} as any)

const DashboardLayoutDashboardIndexRoute =
  DashboardLayoutDashboardIndexImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const ChatLayoutChatIndexRoute = ChatLayoutChatIndexImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => ChatLayoutRoute,
} as any)

const ChatLayoutChatIdRoute = ChatLayoutChatIdImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => ChatLayoutRoute,
} as any)

const DashboardLayoutDashboardUsersIndexRoute =
  DashboardLayoutDashboardUsersIndexImport.update({
    id: '/dashboard/users/',
    path: '/dashboard/users/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardSettingsIndexRoute =
  DashboardLayoutDashboardSettingsIndexImport.update({
    id: '/dashboard/settings/',
    path: '/dashboard/settings/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardUsersCreateRoute =
  DashboardLayoutDashboardUsersCreateImport.update({
    id: '/dashboard/users/create',
    path: '/dashboard/users/create',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardSettingsSuccessRoute =
  DashboardLayoutDashboardSettingsSuccessImport.update({
    id: '/dashboard/settings/success',
    path: '/dashboard/settings/success',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardUsersUpdateIdRoute =
  DashboardLayoutDashboardUsersUpdateIdImport.update({
    id: '/dashboard/users/update/$id',
    path: '/dashboard/users/update/$id',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardUsersDeleteSuccessRoute =
  DashboardLayoutDashboardUsersDeleteSuccessImport.update({
    id: '/dashboard/users/delete/success',
    path: '/dashboard/users/delete/success',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardUsersDeleteIdRoute =
  DashboardLayoutDashboardUsersDeleteIdImport.update({
    id: '/dashboard/users/delete/$id',
    path: '/dashboard/users/delete/$id',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatImport
      parentRoute: typeof rootRoute
    }
    '/_chatLayout': {
      id: '/_chatLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ChatLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_dashboardLayout': {
      id: '/_dashboardLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardLayoutImport
      parentRoute: typeof rootRoute
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundImport
      parentRoute: typeof rootRoute
    }
    '/login/success': {
      id: '/login/success'
      path: '/login/success'
      fullPath: '/login/success'
      preLoaderRoute: typeof LoginSuccessImport
      parentRoute: typeof rootRoute
    }
    '/registration/cancel': {
      id: '/registration/cancel'
      path: '/registration/cancel'
      fullPath: '/registration/cancel'
      preLoaderRoute: typeof RegistrationCancelImport
      parentRoute: typeof rootRoute
    }
    '/registration/confirm': {
      id: '/registration/confirm'
      path: '/registration/confirm'
      fullPath: '/registration/confirm'
      preLoaderRoute: typeof RegistrationConfirmImport
      parentRoute: typeof rootRoute
    }
    '/registration/error': {
      id: '/registration/error'
      path: '/registration/error'
      fullPath: '/registration/error'
      preLoaderRoute: typeof RegistrationErrorImport
      parentRoute: typeof rootRoute
    }
    '/registration/success': {
      id: '/registration/success'
      path: '/registration/success'
      fullPath: '/registration/success'
      preLoaderRoute: typeof RegistrationSuccessImport
      parentRoute: typeof rootRoute
    }
    '/logout/': {
      id: '/logout/'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutIndexImport
      parentRoute: typeof rootRoute
    }
    '/registration/': {
      id: '/registration/'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationIndexImport
      parentRoute: typeof rootRoute
    }
    '/_chatLayout/chat/$id': {
      id: '/_chatLayout/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatLayoutChatIdImport
      parentRoute: typeof ChatLayoutImport
    }
    '/_chatLayout/chat/': {
      id: '/_chatLayout/chat/'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatLayoutChatIndexImport
      parentRoute: typeof ChatLayoutImport
    }
    '/_dashboardLayout/dashboard/': {
      id: '/_dashboardLayout/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutDashboardIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboardLayout/dashboard/settings/success': {
      id: '/_dashboardLayout/dashboard/settings/success'
      path: '/dashboard/settings/success'
      fullPath: '/dashboard/settings/success'
      preLoaderRoute: typeof DashboardLayoutDashboardSettingsSuccessImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboardLayout/dashboard/users/create': {
      id: '/_dashboardLayout/dashboard/users/create'
      path: '/dashboard/users/create'
      fullPath: '/dashboard/users/create'
      preLoaderRoute: typeof DashboardLayoutDashboardUsersCreateImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboardLayout/dashboard/settings/': {
      id: '/_dashboardLayout/dashboard/settings/'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardLayoutDashboardSettingsIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboardLayout/dashboard/users/': {
      id: '/_dashboardLayout/dashboard/users/'
      path: '/dashboard/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardLayoutDashboardUsersIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboardLayout/dashboard/users/delete/$id': {
      id: '/_dashboardLayout/dashboard/users/delete/$id'
      path: '/dashboard/users/delete/$id'
      fullPath: '/dashboard/users/delete/$id'
      preLoaderRoute: typeof DashboardLayoutDashboardUsersDeleteIdImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboardLayout/dashboard/users/delete/success': {
      id: '/_dashboardLayout/dashboard/users/delete/success'
      path: '/dashboard/users/delete/success'
      fullPath: '/dashboard/users/delete/success'
      preLoaderRoute: typeof DashboardLayoutDashboardUsersDeleteSuccessImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboardLayout/dashboard/users/update/$id': {
      id: '/_dashboardLayout/dashboard/users/update/$id'
      path: '/dashboard/users/update/$id'
      fullPath: '/dashboard/users/update/$id'
      preLoaderRoute: typeof DashboardLayoutDashboardUsersUpdateIdImport
      parentRoute: typeof DashboardLayoutImport
    }
  }
}

// Create and export the route tree

interface ChatLayoutRouteChildren {
  ChatLayoutChatIdRoute: typeof ChatLayoutChatIdRoute
  ChatLayoutChatIndexRoute: typeof ChatLayoutChatIndexRoute
}

const ChatLayoutRouteChildren: ChatLayoutRouteChildren = {
  ChatLayoutChatIdRoute: ChatLayoutChatIdRoute,
  ChatLayoutChatIndexRoute: ChatLayoutChatIndexRoute,
}

const ChatLayoutRouteWithChildren = ChatLayoutRoute._addFileChildren(
  ChatLayoutRouteChildren,
)

interface DashboardLayoutRouteChildren {
  DashboardLayoutDashboardIndexRoute: typeof DashboardLayoutDashboardIndexRoute
  DashboardLayoutDashboardSettingsSuccessRoute: typeof DashboardLayoutDashboardSettingsSuccessRoute
  DashboardLayoutDashboardUsersCreateRoute: typeof DashboardLayoutDashboardUsersCreateRoute
  DashboardLayoutDashboardSettingsIndexRoute: typeof DashboardLayoutDashboardSettingsIndexRoute
  DashboardLayoutDashboardUsersIndexRoute: typeof DashboardLayoutDashboardUsersIndexRoute
  DashboardLayoutDashboardUsersDeleteIdRoute: typeof DashboardLayoutDashboardUsersDeleteIdRoute
  DashboardLayoutDashboardUsersDeleteSuccessRoute: typeof DashboardLayoutDashboardUsersDeleteSuccessRoute
  DashboardLayoutDashboardUsersUpdateIdRoute: typeof DashboardLayoutDashboardUsersUpdateIdRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardLayoutDashboardIndexRoute: DashboardLayoutDashboardIndexRoute,
  DashboardLayoutDashboardSettingsSuccessRoute:
    DashboardLayoutDashboardSettingsSuccessRoute,
  DashboardLayoutDashboardUsersCreateRoute:
    DashboardLayoutDashboardUsersCreateRoute,
  DashboardLayoutDashboardSettingsIndexRoute:
    DashboardLayoutDashboardSettingsIndexRoute,
  DashboardLayoutDashboardUsersIndexRoute:
    DashboardLayoutDashboardUsersIndexRoute,
  DashboardLayoutDashboardUsersDeleteIdRoute:
    DashboardLayoutDashboardUsersDeleteIdRoute,
  DashboardLayoutDashboardUsersDeleteSuccessRoute:
    DashboardLayoutDashboardUsersDeleteSuccessRoute,
  DashboardLayoutDashboardUsersUpdateIdRoute:
    DashboardLayoutDashboardUsersUpdateIdRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '': typeof DashboardLayoutRouteWithChildren
  '/not-found': typeof NotFoundRoute
  '/login/success': typeof LoginSuccessRoute
  '/registration/cancel': typeof RegistrationCancelRoute
  '/registration/confirm': typeof RegistrationConfirmRoute
  '/registration/error': typeof RegistrationErrorRoute
  '/registration/success': typeof RegistrationSuccessRoute
  '/logout': typeof LogoutIndexRoute
  '/registration': typeof RegistrationIndexRoute
  '/chat/$id': typeof ChatLayoutChatIdRoute
  '/chat': typeof ChatLayoutChatIndexRoute
  '/dashboard': typeof DashboardLayoutDashboardIndexRoute
  '/dashboard/settings/success': typeof DashboardLayoutDashboardSettingsSuccessRoute
  '/dashboard/users/create': typeof DashboardLayoutDashboardUsersCreateRoute
  '/dashboard/settings': typeof DashboardLayoutDashboardSettingsIndexRoute
  '/dashboard/users': typeof DashboardLayoutDashboardUsersIndexRoute
  '/dashboard/users/delete/$id': typeof DashboardLayoutDashboardUsersDeleteIdRoute
  '/dashboard/users/delete/success': typeof DashboardLayoutDashboardUsersDeleteSuccessRoute
  '/dashboard/users/update/$id': typeof DashboardLayoutDashboardUsersUpdateIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '': typeof DashboardLayoutRouteWithChildren
  '/not-found': typeof NotFoundRoute
  '/login/success': typeof LoginSuccessRoute
  '/registration/cancel': typeof RegistrationCancelRoute
  '/registration/confirm': typeof RegistrationConfirmRoute
  '/registration/error': typeof RegistrationErrorRoute
  '/registration/success': typeof RegistrationSuccessRoute
  '/logout': typeof LogoutIndexRoute
  '/registration': typeof RegistrationIndexRoute
  '/chat/$id': typeof ChatLayoutChatIdRoute
  '/chat': typeof ChatLayoutChatIndexRoute
  '/dashboard': typeof DashboardLayoutDashboardIndexRoute
  '/dashboard/settings/success': typeof DashboardLayoutDashboardSettingsSuccessRoute
  '/dashboard/users/create': typeof DashboardLayoutDashboardUsersCreateRoute
  '/dashboard/settings': typeof DashboardLayoutDashboardSettingsIndexRoute
  '/dashboard/users': typeof DashboardLayoutDashboardUsersIndexRoute
  '/dashboard/users/delete/$id': typeof DashboardLayoutDashboardUsersDeleteIdRoute
  '/dashboard/users/delete/success': typeof DashboardLayoutDashboardUsersDeleteSuccessRoute
  '/dashboard/users/update/$id': typeof DashboardLayoutDashboardUsersUpdateIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_chatLayout': typeof ChatLayoutRouteWithChildren
  '/_dashboardLayout': typeof DashboardLayoutRouteWithChildren
  '/not-found': typeof NotFoundRoute
  '/login/success': typeof LoginSuccessRoute
  '/registration/cancel': typeof RegistrationCancelRoute
  '/registration/confirm': typeof RegistrationConfirmRoute
  '/registration/error': typeof RegistrationErrorRoute
  '/registration/success': typeof RegistrationSuccessRoute
  '/logout/': typeof LogoutIndexRoute
  '/registration/': typeof RegistrationIndexRoute
  '/_chatLayout/chat/$id': typeof ChatLayoutChatIdRoute
  '/_chatLayout/chat/': typeof ChatLayoutChatIndexRoute
  '/_dashboardLayout/dashboard/': typeof DashboardLayoutDashboardIndexRoute
  '/_dashboardLayout/dashboard/settings/success': typeof DashboardLayoutDashboardSettingsSuccessRoute
  '/_dashboardLayout/dashboard/users/create': typeof DashboardLayoutDashboardUsersCreateRoute
  '/_dashboardLayout/dashboard/settings/': typeof DashboardLayoutDashboardSettingsIndexRoute
  '/_dashboardLayout/dashboard/users/': typeof DashboardLayoutDashboardUsersIndexRoute
  '/_dashboardLayout/dashboard/users/delete/$id': typeof DashboardLayoutDashboardUsersDeleteIdRoute
  '/_dashboardLayout/dashboard/users/delete/success': typeof DashboardLayoutDashboardUsersDeleteSuccessRoute
  '/_dashboardLayout/dashboard/users/update/$id': typeof DashboardLayoutDashboardUsersUpdateIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | ''
    | '/not-found'
    | '/login/success'
    | '/registration/cancel'
    | '/registration/confirm'
    | '/registration/error'
    | '/registration/success'
    | '/logout'
    | '/registration'
    | '/chat/$id'
    | '/chat'
    | '/dashboard'
    | '/dashboard/settings/success'
    | '/dashboard/users/create'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard/users/delete/$id'
    | '/dashboard/users/delete/success'
    | '/dashboard/users/update/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | ''
    | '/not-found'
    | '/login/success'
    | '/registration/cancel'
    | '/registration/confirm'
    | '/registration/error'
    | '/registration/success'
    | '/logout'
    | '/registration'
    | '/chat/$id'
    | '/chat'
    | '/dashboard'
    | '/dashboard/settings/success'
    | '/dashboard/users/create'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard/users/delete/$id'
    | '/dashboard/users/delete/success'
    | '/dashboard/users/update/$id'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_chatLayout'
    | '/_dashboardLayout'
    | '/not-found'
    | '/login/success'
    | '/registration/cancel'
    | '/registration/confirm'
    | '/registration/error'
    | '/registration/success'
    | '/logout/'
    | '/registration/'
    | '/_chatLayout/chat/$id'
    | '/_chatLayout/chat/'
    | '/_dashboardLayout/dashboard/'
    | '/_dashboardLayout/dashboard/settings/success'
    | '/_dashboardLayout/dashboard/users/create'
    | '/_dashboardLayout/dashboard/settings/'
    | '/_dashboardLayout/dashboard/users/'
    | '/_dashboardLayout/dashboard/users/delete/$id'
    | '/_dashboardLayout/dashboard/users/delete/success'
    | '/_dashboardLayout/dashboard/users/update/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ChatLayoutRoute: typeof ChatLayoutRouteWithChildren
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  NotFoundRoute: typeof NotFoundRoute
  LoginSuccessRoute: typeof LoginSuccessRoute
  RegistrationCancelRoute: typeof RegistrationCancelRoute
  RegistrationConfirmRoute: typeof RegistrationConfirmRoute
  RegistrationErrorRoute: typeof RegistrationErrorRoute
  RegistrationSuccessRoute: typeof RegistrationSuccessRoute
  LogoutIndexRoute: typeof LogoutIndexRoute
  RegistrationIndexRoute: typeof RegistrationIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ChatLayoutRoute: ChatLayoutRouteWithChildren,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  NotFoundRoute: NotFoundRoute,
  LoginSuccessRoute: LoginSuccessRoute,
  RegistrationCancelRoute: RegistrationCancelRoute,
  RegistrationConfirmRoute: RegistrationConfirmRoute,
  RegistrationErrorRoute: RegistrationErrorRoute,
  RegistrationSuccessRoute: RegistrationSuccessRoute,
  LogoutIndexRoute: LogoutIndexRoute,
  RegistrationIndexRoute: RegistrationIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$",
        "/_chatLayout",
        "/_dashboardLayout",
        "/not-found",
        "/login/success",
        "/registration/cancel",
        "/registration/confirm",
        "/registration/error",
        "/registration/success",
        "/logout/",
        "/registration/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$": {
      "filePath": "$.tsx"
    },
    "/_chatLayout": {
      "filePath": "_chatLayout.tsx",
      "children": [
        "/_chatLayout/chat/$id",
        "/_chatLayout/chat/"
      ]
    },
    "/_dashboardLayout": {
      "filePath": "_dashboardLayout.tsx",
      "children": [
        "/_dashboardLayout/dashboard/",
        "/_dashboardLayout/dashboard/settings/success",
        "/_dashboardLayout/dashboard/users/create",
        "/_dashboardLayout/dashboard/settings/",
        "/_dashboardLayout/dashboard/users/",
        "/_dashboardLayout/dashboard/users/delete/$id",
        "/_dashboardLayout/dashboard/users/delete/success",
        "/_dashboardLayout/dashboard/users/update/$id"
      ]
    },
    "/not-found": {
      "filePath": "not-found.tsx"
    },
    "/login/success": {
      "filePath": "login/success.tsx"
    },
    "/registration/cancel": {
      "filePath": "registration/cancel.tsx"
    },
    "/registration/confirm": {
      "filePath": "registration/confirm.tsx"
    },
    "/registration/error": {
      "filePath": "registration/error.tsx"
    },
    "/registration/success": {
      "filePath": "registration/success.tsx"
    },
    "/logout/": {
      "filePath": "logout/index.tsx"
    },
    "/registration/": {
      "filePath": "registration/index.tsx"
    },
    "/_chatLayout/chat/$id": {
      "filePath": "_chatLayout/chat/$id.tsx",
      "parent": "/_chatLayout"
    },
    "/_chatLayout/chat/": {
      "filePath": "_chatLayout/chat/index.tsx",
      "parent": "/_chatLayout"
    },
    "/_dashboardLayout/dashboard/": {
      "filePath": "_dashboardLayout/dashboard/index.tsx",
      "parent": "/_dashboardLayout"
    },
    "/_dashboardLayout/dashboard/settings/success": {
      "filePath": "_dashboardLayout/dashboard/settings/success.tsx",
      "parent": "/_dashboardLayout"
    },
    "/_dashboardLayout/dashboard/users/create": {
      "filePath": "_dashboardLayout/dashboard/users/create.tsx",
      "parent": "/_dashboardLayout"
    },
    "/_dashboardLayout/dashboard/settings/": {
      "filePath": "_dashboardLayout/dashboard/settings/index.tsx",
      "parent": "/_dashboardLayout"
    },
    "/_dashboardLayout/dashboard/users/": {
      "filePath": "_dashboardLayout/dashboard/users/index.tsx",
      "parent": "/_dashboardLayout"
    },
    "/_dashboardLayout/dashboard/users/delete/$id": {
      "filePath": "_dashboardLayout/dashboard/users/delete/$id.tsx",
      "parent": "/_dashboardLayout"
    },
    "/_dashboardLayout/dashboard/users/delete/success": {
      "filePath": "_dashboardLayout/dashboard/users/delete/success.tsx",
      "parent": "/_dashboardLayout"
    },
    "/_dashboardLayout/dashboard/users/update/$id": {
      "filePath": "_dashboardLayout/dashboard/users/update/$id.tsx",
      "parent": "/_dashboardLayout"
    }
  }
}
ROUTE_MANIFEST_END */
